### ISSUE TITLE
Uniform way of overriding Chart values

### ISSUE THREAD

**Issue by anarsen** [nuuday/terraform-aws-eks-addons#47]
I'm tired of adding minor changes to accommodate for a few extra Chart values :sob: 

## Proposal

All add-on modules already provide default Chart values - kind of. I propose a way of overriding them from the call site:

```terraform
module "prometheus" {
  source = "...//modules/prometheus?ref=v0.8.6"

  values_override = {
    nodeExporter = {
      tolerations = [
        {
          key      = "some-key"
          operator = "Exists"
          effect   = "NoSchedule"
        }
      ]
    }
  }

  # other variables omitted for brevity
}
```

the module will then do

```terraform
helm_release "prometheus" {
  # ..

  values = [yamlencode(local.default_values), yamlencode(var.values_override)]
}
```

**EDIT** I know the `prometheus` sub-module already does this. This issue poses the question _should we not do it for all sub-modules?_

**Comment by wolffberg** [comment]
I think this looks good and simple.

**Comment by wolffberg** [comment]
~@qvistgaard do you think we could go ahead with this?~

It looks like this was already implemented [here](https://github.com/nuuday/terraform-aws-eks-addons/blob/ba0182ff6e1b5037f2715b6f95fc18d199a8668b/modules/prometheus/variables.tf#L65) and [here](https://github.com/nuuday/terraform-aws-eks-addons/blob/ba0182ff6e1b5037f2715b6f95fc18d199a8668b/modules/prometheus/main.tf#L73) although I think we should rewrite it so that the default would be an empty map instead of an empty list.

**Comment by qvistgaard** [comment]
Fine with me, let's do it, however in some cases it might make sense to have some of the defaults as variables, but it should not be the norm
